# Generated by Django 3.1.11 on 2021-05-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100, verbose_name='school')),
                ('place', models.CharField(max_length=100, verbose_name='place')),
                ('period', models.CharField(max_length=100, verbose_name='period')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=100, verbose_name='occupation')),
                ('company', models.CharField(max_length=100, verbose_name='company')),
                ('description', models.TextField(verbose_name='description')),
                ('place', models.CharField(max_length=100, verbose_name='place')),
                ('period', models.CharField(max_length=100, verbose_name='period')),
            ],
        ),
    ]
