# Generated by Django 3.1.11 on 2021-05-26 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_education_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='course',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='course'),
            preserve_default=False,
        ),
    ]
