# Generated by Django 3.1.11 on 2021-05-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_education_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Software')),
                ('level', models.CharField(max_length=100, verbose_name='level')),
                ('percentage', models.IntegerField(verbose_name='percentage')),
            ],
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Technical')),
                ('level', models.CharField(max_length=100, verbose_name='level')),
                ('percentage', models.IntegerField(verbose_name='percentage')),
            ],
        ),
    ]
